# Generated by Django 4.2.13 on 2024-06-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_old',
        ),
    ]
