# Generated by Django 4.2.13 on 2024-06-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='UUID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
