# Generated by Django 4.2.13 on 2024-06-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personPage', '0003_remove_list_items_list_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personPage.item'),
        ),
    ]
