# Generated by Django 4.2.13 on 2024-06-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personPage', '0006_test_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_table',
        ),
    ]
